global:
  resolve_timeout: 5m

receivers:
  - name: 'webhook'
    webhook_configs:
      - url: 'http://localhost:5001/'  # Webhook listener for Ansible

route:
  receiver: 'webhook'
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1m
