global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert.rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'blackbox_exporter'
    static_configs:
      - targets: ['localhost:9115']

  - job_name: 'nginx_http_check'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets: ['http://localhost']
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: localhost:9115

